# Generated by Django 4.2.3 on 2023-07-23 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=60)),
                ('file', models.FileField(blank=True, null=True, upload_to='resume')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=60)),
                ('proj_intro', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField()),
                ('proj_img1', models.ImageField(blank=True, null=True, upload_to='projects/proj_img1')),
                ('proj_img2', models.ImageField(blank=True, null=True, upload_to='projects/proj_img2')),
                ('proj_img3', models.ImageField(blank=True, null=True, upload_to='projects/proj_img3')),
                ('client', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('github_link', models.URLField(default='')),
                ('project_url', models.URLField(default='')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('date_created', models.DateField()),
                ('category', models.ManyToManyField(blank=True, to='myproject.category')),
            ],
        ),
    ]
