# Generated by Django 4.2.3 on 2023-07-19 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('proj_img', models.ImageField(blank=True, null=True, upload_to='projects')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
