# Generated by Django 4.2.3 on 2023-07-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0003_rename_resume_resume_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='client',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='project_url',
            field=models.URLField(default=''),
        ),
    ]
