# Generated by Django 4.2.3 on 2023-07-21 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0004_portfolio_client_portfolio_project_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='proj_img',
            new_name='proj_img1',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='proj_img2',
            field=models.ImageField(blank=True, null=True, upload_to='projects'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='proj_img3',
            field=models.ImageField(blank=True, null=True, upload_to='projects'),
        ),
    ]
