# Generated by Django 4.2.3 on 2023-07-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0005_rename_proj_img_portfolio_proj_img1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='portfolio',
            name='category',
            field=models.ManyToManyField(null=True, to='myproject.category'),
        ),
    ]
