# Generated by Django 4.2.3 on 2023-07-21 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0010_alter_resume_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Portfolio',
            new_name='Project',
        ),
    ]
