# Generated by Django 4.2.3 on 2023-07-21 22:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0011_rename_portfolio_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
