# Generated by Django 4.2.3 on 2023-07-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0014_alter_project_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
