# Generated by Django 4.2.3 on 2023-07-22 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0015_alter_project_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='proj_intro',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
