# Generated by Django 4.2.3 on 2023-07-12 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('authname', models.CharField(max_length=15)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
