# Generated by Django 4.2.3 on 2023-07-12 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_blogs_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='time_created',
            new_name='timeStamp',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='image',
        ),
        migrations.AddField(
            model_name='blogs',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='blog'),
        ),
    ]
